services:
  axum:
    container_name: axum
    build: .
    ports:
      - "5000:5000"
    depends_on:
      pgdb:
        condition: service_healthy
    environment:
      CARGO_TERM_COLOR: always
  pgdb:
    container_name: pgdb
    image: postgres:17
    environment:
      POSTGRES_DB: rest_api
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 4s
      retries: 1
volumes:
  pgdata:
